### ISSUE TITLE
Failed to establish a new connection: [Errno -3] Try again

### ISSUE THREAD

**Issue by tunip** [joerg65/pytedee#5]
Home Assistant: 2021.2.3
Latest: pytedee & custom tedee integration

The Lock could be controlled by HA and the status are updated frequently fine.
But every few minutes I see this in the Home Assistant log (maybe a connection limit from the tedee API):
```
2021-02-17 21:27:46,133 - homeassistant.helpers.entity - ERROR - Update for lock.haustur fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f82ac0369a0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.tedee.com', port=443): Max retries exceeded with url: /api/v1.15/my/lock/sync (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f82ac0369a0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tedee_lock/lock.py", line 88, in update
    self._available = self._client.update(self._lock_id)
  File "/var/tmp/homeassistant-venv/lib/python3.8/site-packages/pytedee/TedeeClient.py", line 225, in update
    self.get_state()
  File "/var/tmp/homeassistant-venv/lib/python3.8/site-packages/pytedee/TedeeClient.py", line 187, in get_state
    r = requests.get(api_url_state, headers=self._api_header)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.tedee.com', port=443): Max retries exceeded with url: /api/v1.15/my/lock/sync (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f82ac0369a0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-02-17 21:27:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for lock.haustur fails
```

**Comment by joerg65** [comment]
As of my opinion it's a issue of tedee server.
I see in my logs the same, last today at 03:24h.

**Comment by tunip** [comment]
It looks like with HA 2021.3 it happens not so often. Hopefully tedee could increase the count of requests. Otherwise a small connection limit in pytedee would maybe help.
